version: "3.7"

services:
    nginx:
        build: back/docker/nginx
        restart: on-failure
        volumes:
            - ./back:/var/www/api:delegated
            - ./back/var/logs/nginx/:/var/log/nginx
            - ./back/docker/nginx/api.conf:/etc/nginx/conf.d/default.conf
            - ./back/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '90:80'
    api:
        build: back/docker/php
        restart: on-failure
        volumes:
            - ./back:/var/www/api:delegated
            - ./back/docker/php/php.ini:/usr/local/etc/php/php.ini:ro
        depends_on:
            - nginx
    front:
        build: front
        restart: on-failure
        command: "npm start"
        depends_on:
            - api
        ports:
            - '3000:3000'
        volumes:
            - ./front:/var/www/ui:delegated
            - nodemodules:/var/www/ui/node_modules
volumes:
    nodemodules: {}
